import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
const RSS = ({ data }) => {
    const hasItunes = data.itunes_author || data.itunes_category || (data.item && data.item.some((i) => i.itunes_item_image || i.itunes_duration));
    const hasMedia = data.item?.some((i) => i.media);
    const isTelegramLink = data.link?.startsWith('https://t.me/s/');
    return (_jsx("rss", { "xmlns:atom": "http://www.w3.org/2005/Atom", "xmlns:itunes": hasItunes ? 'http://www.itunes.com/dtds/podcast-1.0.dtd' : undefined, "xmlns:media": hasMedia ? 'http://search.yahoo.com/mrss/' : undefined, version: "2.0", children: _jsxs("channel", { children: [_jsx("title", { children: data.title || 'RSSHub' }), _jsx("link", { children: data.link || 'https://docs.rsshub.app' }), _jsx("atom:link", { href: data.atomlink, rel: "self", type: "application/rss+xml" }), _jsxs("description", { children: [data.description || data.title, " - Powered by RSSHub"] }), _jsx("generator", { children: "RSSHub" }), _jsx("webMaster", { children: "contact@rsshub.app (RSSHub)" }), data.itunes_author && _jsx("itunes:author", { children: data.itunes_author }), data.itunes_category && _jsx("itunes:category", { text: data.itunes_category }), data.itunes_author && _jsx("itunes:explicit", { children: data.itunes_explicit || 'false' }), _jsx("language", { children: data.language || 'en' }), data.image && (_jsxs("image", { children: [_jsx("url", { children: data.image }), _jsx("title", { children: data.title || 'RSSHub' }), _jsx("link", { children: data.link }), isTelegramLink && (_jsxs(_Fragment, { children: [_jsx("height", { children: "31" }), _jsx("width", { children: "88" })] }))] })), _jsx("lastBuildDate", { children: data.lastBuildDate }), _jsx("ttl", { children: data.ttl }), data.item?.map((item) => (_jsxs("item", { children: [_jsx("title", { children: item.title }), _jsx("description", { children: item.description }), _jsx("link", { children: item.link }), _jsx("guid", { isPermaLink: "false", children: item.guid || item.link || item.title }), item.pubDate && _jsx("pubDate", { children: item.pubDate }), item.author && _jsx("author", { children: item.author }), item.image && _jsx("enclosure", { url: item.image, type: "image/jpeg" }), item.itunes_item_image && _jsx("itunes:image", { href: item.itunes_item_image }), item.enclosure_url && _jsx("enclosure", { url: item.enclosure_url, length: item.enclosure_length, type: item.enclosure_type }), item.itunes_duration && _jsx("itunes:duration", { children: item.itunes_duration }), typeof item.category === 'string' ? _jsx("category", { children: item.category }) : item.category?.map((c) => _jsx("category", { children: c })), item.media &&
                            Object.entries(item.media).map(([key, value]) => {
                                const Tag = `media:${key}`;
                                return _jsx(Tag, { ...value });
                            })] })))] }) }));
};
export default RSS;
//# sourceMappingURL=rss.js.map